server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=bankingdb;encrypt=false
    username: sa
    password: YourStrong!Passw0rd1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
